#!/usr/bin/env python3
"""
flux_2d.py
==========

Analytical flux-correction framework for two-dimensional
rectangular domain-decomposition problems.

The methodology reconstructs continuity of

    * solution
    * diffusive flux

across decomposition interfaces by projecting the
interface jumps onto analytical homogeneous modes.

The homogeneous modes satisfy

    k*u - F0 Δu = 0

and decay exponentially away from the interface.

Author
------
Lorenzo Zambelli
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable
from typing import Literal

import numpy as np

from numpy.typing import NDArray


# ==========================================================
# TYPE DEFINITIONS
# ==========================================================

Side = Literal[
    "w",
    "e",
    "n",
    "s",
]

BasisFunction = Callable[
    [
        NDArray[np.float64],
        NDArray[np.float64],
    ],
    NDArray[np.float64],
]

class EigenFunctions2D:
    """
    Generates analytical homogeneous eigenfunctions for
    rectangular reaction-diffusion domains.

    The functions generated by this class satisfy

        k*u - F0 Δu = 0

    and are used as correction modes for enforcing
    continuity of both solution and diffusive flux
    across domain-decomposition interfaces.

    Four families of modes are provided:

        * west_homo
        * east_homo
        * north_homo
        * south_homo

    Each mode decays exponentially away from its
    associated boundary.

    Attributes
    ----------
    a : float
        West boundary coordinate.

    b : float
        East boundary coordinate.

    c : float
        South boundary coordinate.

    d : float
        North boundary coordinate.

    F0 : float
        Constant diffusion coefficient.

    k : float
        Reaction coefficient.

    Lx : float
        Domain length in the x-direction.

    Ly : float
        Domain length in the y-direction.

    mu : float
        Characteristic decay parameter

            mu = sqrt(k/F0)

    Parameters
    ----------
    a : float
        West boundary location.

    b : float
        East boundary location.

    c : float
        South boundary location.

    d : float
        North boundary location.

    F0 : float
        Constant diffusion coefficient.

    k : float
        Constant reaction coefficient.

    Examples
    --------
    >>> ef = EigenFunctions2D(
    ...     a=0.0,
    ...     b=10.0,
    ...     c=0.0,
    ...     d=5.0,
    ...     F0=30.0,
    ...     k=25.0,
    ... )
    >>>
    >>> phi = ef.west_homo(
    ...     n=1,
    ...     x=5.0,
    ...     y=2.5,
    ... )
    """

    def __init__(
        self,
        a: float,
        b: float,
        c: float,
        d: float,
        F0: float,
        k: float,
    ):
        """
        Initialize the analytical eigenfunction generator.

        Parameters
        ----------
        a : float
            West boundary coordinate.

        b : float
            East boundary coordinate.

        c : float
            South boundary coordinate.

        d : float
            North boundary coordinate.

        F0 : float
            Constant diffusion coefficient.

        k : float
            Constant reaction coefficient.

        Examples
        --------
        >>> ef = EigenFunctions2D(
        ...     0.0,
        ...     10.0,
        ...     0.0,
        ...     5.0,
        ...     30.0,
        ...     25.0,
        ... )
        """

        self.a = a
        self.b = b

        self.c = c
        self.d = d

        self.F0 = F0
        self.k = k

        self.Lx = b - a
        self.Ly = d - c

        self.mu = np.sqrt(
            k / F0
        )

    def west_homo(
        self,
        n: int,
        x,
        y,
    ):
        """
        Evaluate the homogeneous mode generated from the
        west boundary.

        The mode satisfies

            k*u - F0 Δu = 0

        and decays exponentially from west to east.

        Parameters
        ----------
        n : int
            Fourier mode number.

        x : float or ndarray
            x-coordinate.

        y : float or ndarray
            y-coordinate.

        Returns
        -------
        float or ndarray
            Value of the west-generated homogeneous mode.

        Notes
        -----
        The analytical form is

            sinh(alpha*(b-x))
            ----------------- sin(beta*(y-c))
             sinh(alpha*Lx)

        where

            beta = n*pi/Ly

        and

            alpha = sqrt(mu² + beta²).

        Examples
        --------
        >>> phi = ef.west_homo(
        ...     n=3,
        ...     x=x,
        ...     y=y,
        ... )
        """

        beta = (
            n * np.pi
            / self.Ly
        )

        alpha = np.sqrt(
            self.mu**2
            + beta**2
        )

        return (
            np.sinh(
                alpha * (self.b - x)
            )
            /
            np.sinh(
                alpha * self.Lx
            )
            *
            np.sin(
                beta * (y - self.c)
            )
        )

    def east_homo(
        self,
        n: int,
        x,
        y,
    ):
        """
        Evaluate the homogeneous mode generated from the
        east boundary.

        The mode satisfies

            k*u - F0 Δu = 0

        and decays exponentially from east to west.

        Parameters
        ----------
        n : int
            Fourier mode number.

        x : float or ndarray
            x-coordinate.

        y : float or ndarray
            y-coordinate.

        Returns
        -------
        float or ndarray
            Value of the east-generated homogeneous mode.

        Notes
        -----
        The analytical form is

            sinh(alpha*(x-a))
            ----------------- sin(beta*(y-c))
             sinh(alpha*Lx)

        where

            beta = n*pi/Ly

        and

            alpha = sqrt(mu² + beta²).

        Examples
        --------
        >>> phi = ef.east_homo(
        ...     n=2,
        ...     x=x,
        ...     y=y,
        ... )
        """

        beta = (
            n * np.pi
            / self.Ly
        )

        alpha = np.sqrt(
            self.mu**2
            + beta**2
        )

        return (
            np.sinh(
                alpha * (x - self.a)
            )
            /
            np.sinh(
                alpha * self.Lx
            )
            *
            np.sin(
                beta * (y - self.c)
            )
        )

    def south_homo(
        self,
        n: int,
        x,
        y,
    ):
        """
        Evaluate the homogeneous mode generated from the
        south boundary.

        The mode satisfies

            k*u - F0 Δu = 0

        and decays exponentially from south to north.

        Parameters
        ----------
        n : int
            Fourier mode number.

        x : float or ndarray
            x-coordinate.

        y : float or ndarray
            y-coordinate.

        Returns
        -------
        float or ndarray
            Value of the south-generated homogeneous mode.

        Notes
        -----
        The analytical form is

            sinh(alpha*(d-y))
            ----------------- sin(gamma*(x-a))
             sinh(alpha*Ly)

        where

            gamma = n*pi/Lx

        and

            alpha = sqrt(mu² + gamma²).

        Examples
        --------
        >>> phi = ef.south_homo(
        ...     n=1,
        ...     x=x,
        ...     y=y,
        ... )
        """

        gamma = (
            n * np.pi
            / self.Lx
        )

        alpha = np.sqrt(
            self.mu**2
            + gamma**2
        )

        return (
            np.sinh(
                alpha * (self.d - y)
            )
            /
            np.sinh(
                alpha * self.Ly
            )
            *
            np.sin(
                gamma * (x - self.a)
            )
        )

    def north_homo(
        self,
        n: int,
        x,
        y,
    ):
        """
        Evaluate the homogeneous mode generated from the
        north boundary.

        The mode satisfies

            k*u - F0 Δu = 0

        and decays exponentially from north to south.

        Parameters
        ----------
        n : int
            Fourier mode number.

        x : float or ndarray
            x-coordinate.

        y : float or ndarray
            y-coordinate.

        Returns
        -------
        float or ndarray
            Value of the north-generated homogeneous mode.

        Notes
        -----
        The analytical form is

            sinh(alpha*(y-c))
            ----------------- sin(gamma*(x-a))
             sinh(alpha*Ly)

        where

            gamma = n*pi/Lx

        and

            alpha = sqrt(mu² + gamma²).

        Examples
        --------
        >>> phi = ef.north_homo(
        ...     n=4,
        ...     x=x,
        ...     y=y,
        ... )
        """

        gamma = (
            n * np.pi
            / self.Lx
        )

        alpha = np.sqrt(self.mu**2+gamma**2)
        return np.sinh(alpha*(y-self.c))/np.sinh(alpha*self.Ly)*np.sin(gamma*(x-self.a))

@dataclass(slots=True)
class Domain2D:
    """
    Represents a rectangular subdomain used in the
    two-dimensional flux-correction framework.

    A Domain2D object contains the geometric information,
    physical parameters, and interface definitions required
    to construct analytical homogeneous correction modes.

    The domain is defined by

        x ∈ [a,b]

        y ∈ [c,d]

    and is governed by the reaction-diffusion operator

        k*u - F0 Δu

    for which analytical homogeneous eigenfunctions are
    available.

    The domain may have one or more active interfaces
    located on its boundaries. These interfaces define the
    correction basis used during interface reconstruction.

    Attributes
    ----------
    a : float
        West boundary coordinate.

    b : float
        East boundary coordinate.

    c : float
        South boundary coordinate.

    d : float
        North boundary coordinate.

    F0 : float
        Constant diffusion coefficient.

    k : float
        Constant reaction coefficient.

    interfaces : tuple[Side, ...]
        Active interface boundaries.

        Allowed values are

            "w" : west interface

            "e" : east interface

            "n" : north interface

            "s" : south interface

    n_modes : int, optional
        Number of Fourier correction modes used on
        each active interface.

        Default is 10.

    Examples
    --------
    Create a domain with a single east interface:

    >>> domain = Domain2D(
    ...     a=0.0,
    ...     b=50.0,
    ...     c=0.0,
    ...     d=20.0,
    ...     F0=30.0,
    ...     k=25.0,
    ...     interfaces=("e",),
    ... )

    Create a domain with both east and north interfaces:

    >>> domain = Domain2D(
    ...     a=0.0,
    ...     b=50.0,
    ...     c=0.0,
    ...     d=20.0,
    ...     F0=30.0,
    ...     k=25.0,
    ...     interfaces=("e", "n"),
    ...     n_modes=20,
    ... )
    """

    a: float
    b: float

    c: float
    d: float

    F0: float
    k: float

    interfaces: tuple[Side, ...]

    n_modes: int = 10

    @property
    def eigenfunctions(self) -> EigenFunctions2D:
        """
        Return the analytical eigenfunction container
        associated with this domain.

        Returns
        -------
        EigenFunctions2D
            Object containing all homogeneous correction
            modes for the current geometry and physical
            parameters.

        Examples
        --------
        >>> ef = domain.eigenfunctions

        >>> phi = ef.east_homo(
        ...     n=1,
        ...     x=x,
        ...     y=y,
        ... )
        """

        return EigenFunctions2D(
            self.a,
            self.b,
            self.c,
            self.d,
            self.F0,
            self.k,
        )

    def basis_functions(
        self,
    ) -> tuple[BasisFunction, ...]:
        """
        Construct the analytical correction basis associated
        with the active interfaces of the domain.

        For each interface and for each Fourier mode,

            n = 1,...,n_modes

        an analytical homogeneous eigenfunction is generated.

        The basis is assembled in the order specified by
        ``self.interfaces``.

        Returns
        -------
        tuple[BasisFunction, ...]
            Collection of callable basis functions.

        Notes
        -----
        If

            interfaces = ("e", "n")

        and

            n_modes = 3

        the basis will contain

            east mode 1
            east mode 2
            east mode 3
            north mode 1
            north mode 2
            north mode 3

        Examples
        --------
        >>> basis = domain.basis_functions()

        >>> value = basisx, y

        >>> len(basis)
        10
        """

        ef = self.eigenfunctions

        basis = []

        for side in self.interfaces:

            for n in range(
                1,
                self.n_modes + 1,
            ):

                if side == "w":

                    basis.append(
                        lambda x, y,
                        n=n,
                        ef=ef:
                        ef.west_homo(
                            n,
                            x,
                            y,
                        )
                    )

                elif side == "e":

                    basis.append(
                        lambda x, y,
                        n=n,
                        ef=ef:
                        ef.east_homo(
                            n,
                            x,
                            y,
                        )
                    )

                elif side == "n":

                    basis.append(
                        lambda x, y,
                        n=n,
                        ef=ef:
                        ef.north_homo(
                            n,
                            x,
                            y,
                        )
                    )

                elif side == "s":

                    basis.append(
                        lambda x, y,
                        n=n,
                        ef=ef:
                        ef.south_homo(
                            n,
                            x,
                            y,
                        )
                    )

                else:

                    raise ValueError(
                        f"Unknown interface side '{side}'"
                    )

        return tuple(basis)

    @property
    def n_unknowns(self) -> int:
        """
        Return the total number of correction
        coefficients associated with this domain.

        The number of unknowns is

            (# interfaces)
            ×
            (n_modes)

        Returns
        -------
        int
            Total number of modal amplitudes.

        Examples
        --------
        Single interface:

        >>> domain = Domain2D(
        ...     a=0,
        ...     b=1,
        ...     c=0,
        ...     d=1,
        ...     F0=30,
        ...     k=25,
        ...     interfaces=("e",),
        ...     n_modes=10,
        ... )

        >>> domain.n_unknowns
        10

        Two interfaces:

        >>> domain = Domain2D(
        ...     a=0,
        ...     b=1,
        ...     c=0,
        ...     d=1,
        ...     F0=30,
        ...     k=25,
        ...     interfaces=("e", "n"),
        ...     n_modes=10,
        ... )

        >>> domain.n_unknowns
        20
        """

        return (
            len(self.interfaces)
            * self.n_modes
        )

@dataclass(slots=True)
class DomainSolution2D:
    """
    Container holding the numerical solution associated
    with a two-dimensional subdomain.

    This class stores both the raw finite-element solution
    and the interpolation utilities required by the flux
    reconstruction algorithm.

    The stored interpolators provide continuous access to

        * the solution
        * the x-gradient
        * the y-gradient

    at arbitrary locations inside the subdomain.

    Attributes
    ----------
    domain : Domain2D
        Domain description associated with the solution.

    solution : NDArray[np.float64]
        Degrees of freedom of the numerical solution.

    x : NDArray[np.float64]
        x-coordinates associated with the solution.

    y : NDArray[np.float64]
        y-coordinates associated with the solution.

    interpolator : Callable
        Function returning the interpolated solution

            u(x,y)

        at arbitrary points.

    gradx : Callable
        Function returning

            du/dx

        at arbitrary points.

    grady : Callable
        Function returning

            du/dy

        at arbitrary points.

    Examples
    --------
    Create a domain solution:

    >>> solution = DomainSolution2D(
    ...     domain=domain,
    ...     solution=u,
    ...     x=X,
    ...     y=Y,
    ...     interpolator=interp,
    ...     gradx=grad_x,
    ...     grady=grad_y,
    ... )

    Evaluate the interpolated solution:

    >>> value = solution.interpolator(
    ...     10.0,
    ...     5.0,
    ... )

    Evaluate gradients:

    >>> ux = solution.gradx(
    ...     10.0,
    ...     5.0,
    ... )

    >>> uy = solution.grady(
    ...     10.0,
    ...     5.0,
    ... )
    """

    domain: Domain2D

    solution: NDArray[np.float64]

    x: NDArray[np.float64]
    y: NDArray[np.float64]

    interpolator: Callable

    gradx: Callable
    grady: Callable

    @property
    def basis(
        self,
    ):
        """
        Return the analytical correction basis associated
        with the domain.

        Returns
        -------
        tuple[BasisFunction, ...]
            Analytical homogeneous basis functions used
            for interface correction.

        Examples
        --------
        >>> basis = solution.basis

        >>> phi = basis[0]

        >>> value = phi(
        ...     x,
        ...     y,
        ... )
        """

        return (
            self.domain
            .basis_functions()
        )

    @property
    def n_unknowns(
        self,
    ) -> int:
        """
        Return the number of modal correction coefficients
        associated with the domain.

        Returns
        -------
        int
            Total number of correction amplitudes.

        Examples
        --------
        >>> solution.n_unknowns
        20
        """

        return (
            self.domain
            .n_unknowns
        )


@dataclass(slots=True)
class FluxCorrectionResult2D:
    """
    Stores the outcome of a two-dimensional flux-correction
    reconstruction.

    Following the solution of the modal least-squares system,
    the correction amplitudes, reconstructed correction fields,
    corrected solutions, and assembled matrices are collected
    inside this container.

    Attributes
    ----------
    coefficients : NDArray[np.float64]
        Vector of modal amplitudes obtained from the
        least-squares solution.

        The coefficients are ordered according to the
        correction basis used during assembly.

    corrections : tuple
        Correction fields generated on the participating
        subdomains.

        For a two-domain correction this typically contains

            (
                correction_west,
                correction_east
            )

        or

            (
                correction_south,
                correction_north
            )

        depending on the interface orientation.

    corrected : tuple
        Corrected numerical solutions obtained after
        subtracting the reconstructed homogeneous
        corrections.

        Typically

            corrected_solution
            =
            original_solution
            -
            correction

    matrix : NDArray[np.float64]
        Global least-squares system matrix.

        This matrix represents the projection of
        interface jumps onto the analytical correction
        basis.

    rhs : NDArray[np.float64]
        Right-hand-side vector generated from the
        projected solution and flux jumps.

    Examples
    --------
    Solve a correction problem:

    >>> result = FluxInterfaceCorrector2D.correct(
    ...     domains,
    ...     y_interface,
    ...     x_interface,
    ... )

    Access the modal coefficients:

    >>> coeffs = result.coefficients

    Access the corrected solutions:

    >>> u_west = result.corrected[0]

    >>> u_east = result.corrected[1]

    Access the least-squares system:

    >>> A = result.matrix

    >>> b = result.rhs
    """

    coefficients: NDArray[np.float64]

    corrections: tuple

    corrected: tuple

    matrix: NDArray[np.float64]

    rhs: NDArray[np.float64]



class FluxInterfaceCorrector2D:
    """
    Performs analytical flux correction across a vertical
    interface separating two rectangular subdomains.

    The correction is constructed by projecting both the
    solution jump

        Ju

    and the diffusive flux jump

        Jq

    onto a set of analytical homogeneous correction modes.

    The resulting least-squares system determines the modal
    amplitudes required to reconstruct continuity of

        * solution
        * normal flux

    at the interface.

    The homogeneous correction modes satisfy

        k*u - F0 Δu = 0

    and therefore modify the numerical solution without
    altering the governing equation.

    Notes
    -----
    The current implementation assumes a vertical interface

        x = constant

    separating two neighboring domains.

    Domain 1 is interpreted as the western domain and

    Domain 2 is interpreted as the eastern domain.

    Examples
    --------
    >>> result = FluxInterfaceCorrector2D.correct(
    ...     domains=(west_domain, east_domain),
    ...     y_interface=yline,
    ...     x_interface=xI,
    ... )

    Access the corrected solutions:

    >>> u_west = result.corrected[0]

    >>> u_east = result.corrected[1]

    Access the least-squares system:

    >>> A = result.matrix

    >>> b = result.rhs
    """

    @staticmethod
    def correct(
        domains,
        y_interface,
        x_interface,
    ):
        """
        Compute the analytical interface correction.

        Parameters
        ----------
        domains : tuple[DomainSolution2D, DomainSolution2D]
            Pair of neighboring domain solutions.

            The ordering is

                (
                    west_domain,
                    east_domain
                )

        y_interface : ndarray
            Coordinates along the interface where
            solution and flux jumps are evaluated.

        x_interface : float
            Interface location.

        Returns
        -------
        FluxCorrectionResult2D
            Object containing

                * modal coefficients
                * correction fields
                * corrected solutions
                * assembled matrix
                * assembled right-hand side

        Notes
        -----
        The algorithm proceeds in four stages:

        1. Compute physical interface jumps.

        2. Project jumps onto Fourier modes.

        3. Solve the resulting least-squares problem.

        4. Reconstruct homogeneous correction fields.

        Examples
        --------
        >>> result = (
        ...     FluxInterfaceCorrector2D.correct(
        ...         domains,
        ...         y_interface,
        ...         x_interface,
        ...     )
        ... )
        """

        domain_west, domain_east = domains

        n_modes = (
            domain_west.domain.n_modes
        )

        Ly = (
            domain_west.domain.d
            -
            domain_west.domain.c
        )

        n_unknowns = (
            2 * n_modes
        )

        x_eval = np.full_like(
            y_interface,
            x_interface,
            dtype=float,
        )

        # =====================================================
        # PHYSICAL INTERFACE JUMPS
        # =====================================================

        solution_jump = (
            domain_west.interpolator(
                x_eval,
                y_interface,
            )
            -
            domain_east.interpolator(
                x_eval,
                y_interface,
            )
        )

        flux_jump = (
            domain_west.domain.F0
            *
            domain_west.gradx(
                x_eval,
                y_interface,
            )
            -
            domain_east.domain.F0
            *
            domain_east.gradx(
                x_eval,
                y_interface,
            )
        )

        solution_jump = np.nan_to_num(
            np.asarray(
                solution_jump,
                dtype=float,
            )
        )

        flux_jump = np.nan_to_num(
            np.asarray(
                flux_jump,
                dtype=float,
            )
        )

        y_interface = np.asarray(
            y_interface,
            dtype=float,
        )

        # =====================================================
        # GLOBAL LEAST-SQUARES SYSTEM
        # =====================================================

        A = np.zeros(
            (
                n_unknowns,
                n_unknowns,
            ),
            dtype=float,
        )

        b = np.zeros(
            n_unknowns,
            dtype=float,
        )

        phi_west = (
            domain_west.domain
            .eigenfunctions
            .east_homo
        )

        phi_east = (
            domain_east.domain
            .eigenfunctions
            .west_homo
        )

        h = 1.0e-6

        # =====================================================
        # ASSEMBLY
        # =====================================================

        for n in range(
            1,
            n_modes + 1,
        ):

            psi_n = np.sin(
                n
                *
                np.pi
                *
                y_interface
                /
                Ly
            )

            # -------------------------------------------------
            # RHS: SOLUTION JUMP
            # -------------------------------------------------

            b[n - 1] = -(
                2.0
                /
                Ly
                *
                np.trapezoid(
                    solution_jump
                    *
                    psi_n,
                    y_interface,
                )
            )

            # -------------------------------------------------
            # RHS: FLUX JUMP
            # -------------------------------------------------

            b[
                n_modes + n - 1
            ] = -(
                2.0
                /
                Ly
                *
                np.trapezoid(
                    flux_jump
                    *
                    psi_n,
                    y_interface,
                )
            )

            # -------------------------------------------------
            # MATRIX ASSEMBLY
            # -------------------------------------------------

            for m in range(
                1,
                n_modes + 1,
            ):

                phi_west_m = phi_west(
                    m,
                    x_interface,
                    y_interface,
                )

                phi_east_m = phi_east(
                    m,
                    x_interface,
                    y_interface,
                )

                # ---------------------------------------------
                # SOLUTION CONTINUITY BLOCK
                # ---------------------------------------------

                A[
                    n - 1,
                    m - 1,
                ] = -(
                    2.0
                    /
                    Ly
                    *
                    np.trapezoid(
                        phi_west_m
                        *
                        psi_n,
                        y_interface,
                    )
                )

                A[
                    n - 1,
                    n_modes + m - 1,
                ] = (
                    2.0
                    /
                    Ly
                    *
                    np.trapezoid(
                        phi_east_m
                        *
                        psi_n,
                        y_interface,
                    )
                )

                # ---------------------------------------------
                # GRADIENTS
                # ---------------------------------------------

                dphi_west_m = (
                    phi_west(
                        m,
                        x_interface + h,
                        y_interface,
                    )
                    -
                    phi_west(
                        m,
                        x_interface - h,
                        y_interface,
                    )
                ) / (2.0 * h)

                dphi_east_m = (
                    phi_east(
                        m,
                        x_interface + h,
                        y_interface,
                    )
                    -
                    phi_east(
                        m,
                        x_interface - h,
                        y_interface,
                    )
                ) / (2.0 * h)

                # ---------------------------------------------
                # FLUX CONTINUITY BLOCK
                # ---------------------------------------------

                A[
                    n_modes + n - 1,
                    m - 1,
                ] = -(
                    2.0
                    /
                    Ly
                    *
                    np.trapezoid(
                        domain_west.domain.F0
                        *
                        dphi_west_m
                        *
                        psi_n,
                        y_interface,
                    )
                )

                A[
                    n_modes + n - 1,
                    n_modes + m - 1,
                ] = (
                    2.0
                    /
                    Ly
                    *
                    np.trapezoid(
                        domain_east.domain.F0
                        *
                        dphi_east_m
                        *
                        psi_n,
                        y_interface,
                    )
                )

        # =====================================================
        # LEAST-SQUARES SOLUTION
        # =====================================================

        coefficients, *_ = np.linalg.lstsq(
            A,
            b,
            rcond=None,
        )

        coefficients_west = (
            coefficients[:n_modes]
        )

        coefficients_east = (
            coefficients[n_modes:]
        )

        # =====================================================
        # RECONSTRUCTION
        # =====================================================

        X_west = domain_west.x
        Y_west = domain_west.y

        X_east = domain_east.x
        Y_east = domain_east.y

        correction_west = np.zeros_like(
            domain_west.solution,
            dtype=float,
        )

        correction_east = np.zeros_like(
            domain_east.solution,
            dtype=float,
        )

        for n in range(
            1,
            n_modes + 1,
        ):

            correction_west += (
                coefficients_west[n - 1]
                *
                phi_west(
                    n,
                    X_west,
                    Y_west,
                )
            )

            correction_east += (
                coefficients_east[n - 1]
                *
                phi_east(
                    n,
                    X_east,
                    Y_east,
                )
            )

        return FluxCorrectionResult2D(
            coefficients=coefficients,
            corrections=(
                correction_west,
                correction_east,
            ),
            corrected=(
                domain_west.solution
                -
                correction_west,
                domain_east.solution
                -
                correction_east,
            ),
            matrix=A,
            rhs=b,
        )