"""
overlap_plots.py
================

Author
------
Lorenzo Zambelli

Version
-------
1.0

Description
-----------
Visualization routines specific to the overlap-reconstruction framework.

The figures generated by this module are intended to analyze

* overlap-region behavior,
* interface boundary-condition perturbations,
* homogeneous correction quality,
* particular-solution mismatch,
* West/East reconstruction quality.

Generated Figures
-----------------
interface_bc_comparison.png
    Exact and perturbed interface values.

overlap_detail.png
    Detailed reconstruction inside the overlap region.

homogeneous_correction.png
    True versus reconstructed homogeneous corrections.

particular_solution_mismatch.png
    Validation of the assumption

        upW ≈ upE.

Dependencies
------------
numpy
matplotlib
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# INTERFACE BC COMPARISON
# ============================================================

def plot_interface_bc_comparison(
    x_full,
    u_full,
    xW,
    xE,
    gW_exact,
    gE_exact,
    gW,
    gE,
    run_dir,
):
    """
    Visualize interface-condition perturbations.

    Parameters
    ----------
    x_full : ndarray
        Benchmark coordinates.

    u_full : ndarray
        Benchmark solution.

    xW : float
        West overlap boundary.

    xE : float
        East overlap boundary.

    gW_exact : float
        Exact interface value at xE.

    gE_exact : float
        Exact interface value at xW.

    gW : float
        Perturbed West boundary value.

    gE : float
        Perturbed East boundary value.

    run_dir : Path
        Output directory.
    """

    fig, ax = plt.subplots(
        figsize=(14, 7)
    )

    ax.plot(
        x_full,
        u_full,
        color="black",
        lw=3,
        label="Exact solution",
    )

    ax.scatter(
        [xE],
        [gW_exact],
        s=120,
        color="green",
        label="Exact West interface value",
        zorder=10,
    )

    ax.scatter(
        [xE],
        [gW],
        s=120,
        color="red",
        label="Perturbed West interface value",
        zorder=10,
    )

    ax.scatter(
        [xW],
        [gE_exact],
        s=120,
        color="blue",
        label="Exact East interface value",
        zorder=10,
    )

    ax.scatter(
        [xW],
        [gE],
        s=120,
        color="orange",
        label="Perturbed East interface value",
        zorder=10,
    )

    ax.axvline(
        xW,
        color="gray",
        linestyle="--",
    )

    ax.axvline(
        xE,
        color="gray",
        linestyle="--",
    )

    ax.grid(True)

    ax.set_xlabel("Spatial coordinate x")
    ax.set_ylabel("Solution value")

    ax.legend()

    ax.set_title(
        "Interface Boundary Condition Perturbation"
    )

    plt.tight_layout()

    output_dir = Path(str(run_dir))
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
        )

    plt.savefig(
        output_dir
        /
        "interface_bc_comparison.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# OVERLAP DETAIL
# ============================================================

def plot_overlap_detail(
    x_full,
    u_full,
    x_west,
    u_west,
    u_west_corr,
    x_east,
    u_east,
    u_east_corr,
    xW,
    xE,
    west_improvement,
    east_improvement,
    global_improvement,
    run_dir,
):
    """
    Plot reconstruction quality inside the overlap region.
    """

    fig, ax = plt.subplots(
        figsize=(14, 7)
    )

    pad = 2.0

    ax.plot(
        x_full,
        u_full,
        "k",
        lw=4,
        label="Exact",
    )

    ax.plot(
        x_west,
        u_west,
        "r--",
        lw=2,
        label="West raw",
    )

    ax.plot(
        x_west,
        u_west_corr,
        "r",
        lw=3,
        label="West corrected",
    )

    ax.plot(
        x_east,
        u_east,
        "b--",
        lw=2,
        label="East raw",
    )

    ax.plot(
        x_east,
        u_east_corr,
        "b",
        lw=3,
        label="East corrected",
    )

    ax.axvspan(
        xW,
        xE,
        color="gold",
        alpha=0.25,
        label="Overlap region",
    )

    ax.axvline(
        xW,
        color="gray",
        linestyle="--",
    )

    ax.axvline(
        xE,
        color="gray",
        linestyle="--",
    )

    ax.set_xlim(
        xW - pad,
        xE + pad,
    )

    ax.set_xlabel("Spatial coordinate x")
    ax.set_ylabel("Solution u(x)")

    ax.grid(True)

    text = (
        f"West improvement   = {west_improvement:.2f}x\n"
        f"East improvement   = {east_improvement:.2f}x\n"
        f"Global improvement = {global_improvement:.2f}x"
    )

    ax.text(
        0.02,
        0.98,
        text,
        transform=ax.transAxes,
        va="top",
        bbox=dict(
            facecolor="white",
            alpha=0.85,
        ),
    )

    ax.legend()

    ax.set_title(
        "Overlap Region Detail"
    )

    plt.tight_layout()

    output_dir = Path(str(run_dir))
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
        )

    plt.savefig(
        output_dir
        /
        "overlap_detail.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# HOMOGENEOUS CORRECTION VALIDATION
# ============================================================

def plot_homogeneous_correction(
    x_west,
    true_west,
    reconstructed_west,
    x_east,
    true_east,
    reconstructed_east,
    run_dir,
):
    """
    Compare true and reconstructed homogeneous corrections.
    """

    fig, (ax1, ax2) = plt.subplots(
        2,
        1,
        figsize=(14, 10),
        sharex=False,
    )

    ax1.plot(
        x_west,
        true_west,
        lw=3,
        label="True West correction",
    )

    ax1.plot(
        x_west,
        reconstructed_west,
        "--",
        lw=3,
        label="Reconstructed West correction",
    )

    west_error = np.linalg.norm(
        true_west
        -
        reconstructed_west
    )

    ax1.text(
        0.02,
        0.95,
        f"L2= {west_error:.3e}",
        transform=ax1.transAxes,
        va="top",
        bbox=dict(
            facecolor="white",
            alpha=0.85,
        ),
    )

    ax1.grid(True)
    ax1.legend()

    ax1.set_title(
        "West Homogeneous Correction"
    )

    ax2.plot(
        x_east,
        true_east,
        lw=3,
        label="True East correction",
    )

    ax2.plot(
        x_east,
        reconstructed_east,
        "--",
        lw=3,
        label="Reconstructed East correction",
    )

    east_error = np.linalg.norm(
        true_east
        -
        reconstructed_east
    )

    ax2.text(
        0.02,
        0.95,
        f"L2= {east_error:.3e}",
        transform=ax2.transAxes,
        va="top",
        bbox=dict(
            facecolor="white",
            alpha=0.85,
        ),
    )

    ax2.grid(True)
    ax2.legend()

    ax2.set_title(
        "East Homogeneous Correction"
    )

    plt.tight_layout()

    output_dir = Path(str(run_dir))
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
        )

    plt.savefig(
        output_dir /"homogeneous_correction.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# PARTICULAR SOLUTION MISMATCH
# ============================================================

def plot_particular_solution_mismatch(
    x_obs,
    epsilon_p,
    run_dir,
):
    """
    Plot mismatch unexplained by the reconstructed
    homogeneous correction.

    The quantity

        epsilon_p

    is used to assess the assumption

        upW ≈ upE.
    """

    fig, ax = plt.subplots(
        figsize=(12, 6)
    )

    ax.plot(
        x_obs,
        epsilon_p,
        "o-",
        lw=2,
    )

    mismatch_norm = np.linalg.norm(
        epsilon_p
    )

    ax.text(
        0.02,
        0.95,
        f"L2 mismatch = {mismatch_norm:.3e}",
        transform=ax.transAxes,
        va="top",
        bbox=dict(
            facecolor="white",
            alpha=0.85,
        ),
    )

    ax.grid(True)

    ax.set_xlabel(
        "Observation coordinate"
    )

    ax.set_ylabel(
        "Particular mismatch"
    )

    ax.set_title(
        "Particular Solution Mismatch"
    )

    plt.tight_layout()
    output_dir = Path(str(run_dir))
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
        )

    plt.savefig(
        output_dir
        /
        "particular_solution_mismatch.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)