"""
solution_plots.py
=================

Author
------
Lorenzo Zambelli

Version
-------
1.0

Description
-----------
Global visualization routines for the one-dimensional overlap
reconstruction framework.

The figures generated by this module are intended to evaluate

* reconstruction accuracy,
* interface-correction performance,
* weighted-blending performance,
* global error reduction.

Generated Figures
-----------------
solution_with_error.png
    Exact, uncorrected and reconstructed solutions.

sharp_reconstruction.png
    Exact solution compared with sharp reconstruction.

weight_blending_comparison.png
    Sharp versus weighted overlap assembly.

Dependencies
------------
numpy
matplotlib
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# GLOBAL RECONSTRUCTION
# ============================================================

def plot_solution_with_error(
    x,
    u_exact,
    u_uncorrected,
    u_reconstructed,
    l2_before,
    l2_after,
    improvement,
    run_dir,
):
    """
    Compare exact, uncorrected and reconstructed solutions.

    Parameters
    ----------
    x : ndarray
        Spatial coordinates.

    u_exact : ndarray
        Benchmark solution.

    u_uncorrected : ndarray
        Solution prior to homogeneous correction.

    u_reconstructed : ndarray
        Final weighted reconstruction.

    l2_before : float
        Global error before reconstruction.

    l2_after : float
        Global error after reconstruction.

    improvement : float
        Improvement factor

            l2_before / l2_after.

    run_dir : Path
        Output directory.
    """

    error_before = (
        u_uncorrected
        -
        u_exact
    )

    error_after = (
        u_reconstructed
        -
        u_exact
    )

    fig, ax1 = plt.subplots(
        figsize=(16, 9)
    )

    ax1.plot(
        x,
        u_exact,
        color="black",
        linewidth=4,
        label="Exact solution",
    )

    ax1.plot(
        x,
        u_uncorrected,
        "--",
        color="red",
        linewidth=2,
        label=(
            f"Uncorrected\n"
            f"L2={l2_before:.3e}"
        ),
    )

    ax1.plot(
        x,
        u_reconstructed,
        color="green",
        linewidth=3,
        label=(
            f"Weighted reconstruction\n"
            f"L2={l2_after:.3e}"
        ),
    )

    ax1.set_xlabel(
        "Spatial coordinate x"
    )

    ax1.set_ylabel(
        "Solution u(x)"
    )

    ax1.grid(True)

    ax2 = ax1.twinx()

    ax2.plot(
        x,
        error_before,
        color="darkred",
        linewidth=2,
        alpha=0.8,
        label="Error before",
    )

    ax2.plot(
        x,
        error_after,
        color="darkgreen",
        linewidth=2,
        alpha=0.8,
        label="Error after",
    )

    ax2.set_ylabel(
        "Pointwise Error"
    )

    lines1, labels1 = (
        ax1.get_legend_handles_labels()
    )

    lines2, labels2 = (
        ax2.get_legend_handles_labels()
    )

    ax1.legend(
        lines1 + lines2,
        labels1 + labels2,
        loc="best",
    )

    ax1.set_title(
        "Global Reconstruction\n"
        f"L2 before = {l2_before:.3e}\n"
        f"L2 after  = {l2_after:.3e}\n"
        f"Improvement = {improvement:.2f}x"
    )

    plt.tight_layout()

    plt.savefig(
        Path(run_dir)
        /
        "solution_with_error.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# SHARP RECONSTRUCTION
# ============================================================

def plot_sharp_reconstruction(
    x,
    u_exact,
    u_sharp,
    sharp_error,
    run_dir,
):
    """
    Plot reconstruction assembled using
    a direct interface cut.

    Parameters
    ----------
    x : ndarray
        Coordinates.

    u_exact : ndarray
        Exact benchmark solution.

    u_sharp : ndarray
        Reconstruction using a sharp cut.

    sharp_error : float
        Global L2 error.

    run_dir : Path
        Output directory.
    """

    fig, ax = plt.subplots(
        figsize=(16, 9)
    )

    ax.plot(
        x,
        u_exact,
        color="black",
        linewidth=4,
        label="Exact solution",
    )

    ax.plot(
        x,
        u_sharp,
        color="red",
        linewidth=2,
        linestyle="--",
        label=(
            "Sharp reconstruction\n"
            f"L2={sharp_error:.3e}"
        ),
    )

    ax.grid(True)

    ax.set_xlabel(
        "Spatial coordinate x"
    )

    ax.set_ylabel(
        "Solution u(x)"
    )

    ax.legend()

    ax.set_title(
        "Sharp Interface Reconstruction"
    )

    plt.tight_layout()

    plt.savefig(
        Path(run_dir)
        /
        "sharp_reconstruction.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# SHARP VS WEIGHTED
# ============================================================

def plot_weight_blending_comparison(
    x,
    u_exact,
    u_sharp,
    u_weighted,
    sharp_error,
    weighted_error,
    weighting_gain,
    run_dir,
):
    """
    Compare sharp and weighted assembly.

    Parameters
    ----------
    x : ndarray
        Coordinates.

    u_exact : ndarray
        Benchmark solution.

    u_sharp : ndarray
        Reconstruction obtained using
        a direct cut at the interface.

    u_weighted : ndarray
        Reconstruction obtained using
        overlap blending.

    sharp_error : float
        L2 error of sharp assembly.

    weighted_error : float
        L2 error of weighted assembly.

    weighting_gain : float
        Improvement

            sharp_error / weighted_error.

    run_dir : Path
        Output directory.
    """

    fig, ax = plt.subplots(
        figsize=(16, 9)
    )

    ax.plot(
        x,
        u_exact,
        color="black",
        linewidth=4,
        label="Exact",
    )

    ax.plot(
        x,
        u_sharp,
        "--",
        color="red",
        linewidth=2,
        label=(
            "Sharp assembly\n"
            f"L2={sharp_error:.3e}"
        ),
    )

    ax.plot(
        x,
        u_weighted,
        color="blue",
        linewidth=3,
        label=(
            "Weighted assembly\n"
            f"L2={weighted_error:.3e}"
        ),
    )

    ax.grid(True)

    ax.set_xlabel(
        "Spatial coordinate x"
    )

    ax.set_ylabel(
        "Solution u(x)"
    )

    txt = (
        f"Sharp error    : {sharp_error:.3e}\n"
        f"Weighted error : {weighted_error:.3e}\n"
        f"Gain           : {weighting_gain:.2f}x"
    )

    ax.text(
        0.02,
        0.98,
        txt,
        va="top",
        transform=ax.transAxes,
        bbox=dict(
            facecolor="white",
            alpha=0.90,
        ),
    )

    ax.legend()

    ax.set_title(
        "Sharp vs Weighted Overlap Assembly"
    )

    plt.tight_layout()

    plt.savefig(
        Path(run_dir)
        /
        "weight_blending_comparison.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# GLOBAL ERROR COMPARISON
# ============================================================

def plot_global_error_comparison(
    x,
    u_exact,
    u_uncorrected,
    u_sharp,
    u_weighted,
    run_dir,
):
    """
    Compare error distributions of the three
    reconstruction stages.

    Parameters
    ----------
    x : ndarray
        Coordinates.

    u_exact : ndarray
        Exact solution.

    u_uncorrected : ndarray
        Solution prior to reconstruction.

    u_sharp : ndarray
        Sharp reconstruction.

    u_weighted : ndarray
        Weighted reconstruction.

    run_dir : Path
        Output directory.
    """

    fig, ax = plt.subplots(
        figsize=(16, 9)
    )

    ax.plot(
        x,
        u_uncorrected - u_exact,
        linewidth=2,
        label="Uncorrected error",
    )

    ax.plot(
        x,
        u_sharp - u_exact,
        linewidth=2,
        label="Sharp error",
    )

    ax.plot(
        x,
        u_weighted - u_exact,
        linewidth=2,
        label="Weighted error",
    )

    ax.grid(True)

    ax.set_xlabel(
        "Spatial coordinate x"
    )

    ax.set_ylabel(
        "Pointwise error"
    )

    ax.legend()

    ax.set_title(
        "Error Evolution Throughout Reconstruction"
    )

    plt.tight_layout()

    plt.savefig(
        Path(run_dir)
        /
        "global_error_comparison.png",
        dpi=600,
        bbox_inches="tight",
    )

    plt.close(fig)